### ISSUE TITLE
What are the differences between this implementation and frameworks like aframe

### ISSUE THREAD

**Issue by ripitrust** [teliportme/remixvr#1]
This looks really awesome and informative 

As I am currently developing my project using aframe

it seems both of this project and aframe is implemented on top of three.js ?

**Comment by risonsimon** [comment]
Yes, aframe is built on top of threejs.

Each project of 30 days in VR is made on threejs too. Because, the mission of this project was to show and learn what is possible in VR.

I'm also building [Viewport VR](https://viewportvr.co) to make VR dev much easier.
